<dec f='codebrowser/Include/pyerrors.h' l='198' type='PyObject *'/>
<def f='codebrowser/Objects/exceptions.c' l='1239' macro='1' type='PyObject *'/>
<use f='codebrowser/Objects/exceptions.c' l='2562' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2649' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2650' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2650' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2652' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2652' macro='1' u='r'/>
