<dec f='codebrowser/Include/pyerrors.h' l='197' type='PyObject *'/>
<use f='codebrowser/Modules/_io/_iomodule.c' l='671' u='r' c='PyInit__io'/>
<use f='codebrowser/Modules/_io/_iomodule.c' l='673' u='r' c='PyInit__io'/>
<use f='codebrowser/Modules/_io/bufferedio.c' l='660' u='r' c='_set_BlockingIOError'/>
<use f='codebrowser/Modules/_io/bufferedio.c' l='663' u='r' c='_set_BlockingIOError'/>
<use f='codebrowser/Modules/_io/bufferedio.c' l='676' u='r' c='_buffered_check_blocking_error'/>
<use f='codebrowser/Objects/exceptions.c' l='865' u='r' c='oserror_init'/>
<def f='codebrowser/Objects/exceptions.c' l='1233' macro='1' type='PyObject *'/>
<use f='codebrowser/Objects/exceptions.c' l='2561' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2644' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2645' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2645' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2646' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2646' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2647' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2647' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2648' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2648' macro='1' u='r'/>
