<dec f='codebrowser/Include/pyerrors.h' l='182' type='PyObject *'/>
<def f='codebrowser/Objects/exceptions.c' l='1499' macro='1' type='PyObject *'/>
<use f='codebrowser/Objects/exceptions.c' l='2527' macro='1' u='r'/>
<use f='codebrowser/Objects/exceptions.c' l='2604' macro='1' u='r'/>
<use f='codebrowser/Python/pythonrun.c' l='1286' u='r' c='err_input'/>
<use f='codebrowser/Python/pythonrun.c' l='1325' u='r' c='err_input'/>
<use f='codebrowser/Python/pythonrun.c' l='1329' u='r' c='err_input'/>
